### ISSUE TITLE
How sort lists using recursion?

### ISSUE THREAD

**Issue by bagxi** [bagxi/pythonizer#2]

**Comment by kuzaleks** [comment]
In the same way as you would sort array using recursion. As you may remember, merge sort uses recursion. The only tricky part here is how to perform `merge` using recursion. Please remember that in FP you can not change values of lists. You can only create the new list.

**Comment by bagxi** [comment]
TODO:
'+ []' --> '.append()'

**Comment by bagxi** [comment]
'+ []' --> '.append()' no needed
