### ISSUE TITLE
How pow(complex number)?

### ISSUE THREAD

**Issue by bagxi** [bagxi/pythonizer#3]

**Comment by kuzaleks** [comment]
If you have the complex number (e.g. `c = 1 + 2j`), you can raise it in power in the following way: `print c ** 2  # (-3+4j)`

**Comment by bagxi** [comment]
-[] addition and subtraction of two complex numbers
-[] evaluation of the n-th power of the complex number
-[] evaluation of the n-th power of the complex number
-[] all the comparison operations: ==, !=, <, >, <=, >=

**Comment by bagxi** [comment]
>, <, >=, <= --> TypeError: no ordering relation is defined for Complex numbers
